runtime: full

# use this to clone a public repository automatically
repository: https://github.com/UTx10101/Okteto-IDEx

# set this when using a private repository https://github.com/settings/tokens
# or add a GIT_TOKEN okteto secret
gitToken:

persistence:
  size: 2.5Gi

image:
  repository: okteto.dev/idex
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # If not set it will use the default
  name:

podSecurityContext:
  runAsUser: 1001
  runAsGroup: 1000
  fsGroup: 1001

service:
  type: ClusterIP
  port: 3000 # Default IDEx port

resources:
  limits:
    cpu: "2"
    memory: 4Gi
