runtime: full

# use this to clone a public repository automatically
repository: https://github.com/UTx10101/Okteto-IDEx

# set this when using a private repository https://github.com/settings/tokens
# or add a GIT_TOKEN okteto secret
gitToken:

persistence:
  size: 2.5Gi

resources:
  limits:
    cpu: "2"
    memory: 4Gi

# This is the port that Theia is running on. Change this if you want to use this port instead
service:
  port: 3000 # Default IDEx port
