apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "idex.fullname" . }}
  labels:
    {{- include "idex.labels" . | nindent 4 }}
data:
  creds: |
    #!/bin/bash
    echo username=$GIT_TOKEN
    echo password=""
