{{- if .Values.gitToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idex.fullname" . }}
  labels:
    {{- include "idex.labels" . | nindent 4 }}
type: Opaque
data:
  gitToken: {{ .Values.gitToken | b64enc | quote }}
{{- end -}}
